examples: Fix exceptions due to np.int
Will cause exceptions on recent numpy versions, such as

	AttributeError: module 'numpy' has no attribute 'int'.

At least on numpy 1.24.3
Must be replaced with either np.int32/np.int64